title:            Premkumar Masilamani
tagline:          disrupting the known &amp; the unknown ...
description:      On a journey called Life
url:              http://blog.smileprem.com

author:           Premkumar Masilamani
email:            prem@smileprem.com
mobile:           +91-99862-49904

paginate:         5

markdown:         redcarpet
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:      pygments
safe:             false
lsi:              false

permalink:        /:title/
relative_permalinks: false

img-url:          http://blog.smileprem.com/public/img
download-url:     http://blog.smileprem.com/public/downloads
