title:            Premkumar Masilamani
tagline:          disrupting the known &amp; the unknown ...
description:      On a journey called Life
url:              http://localhost:4000

author:           Premkumar Masilamani
email:            prem@smileprem.com
mobile:           +91-99862-49904
tamil:            http://tamil.smileprem.com
rawvegan:         http://www.raw-vegan-recipes.com
facebook:         https://www.facebook.com/prem82
twitter:          https://twitter.com/prem82
linkedin:         http://www.linkedin.com/in/premkumarmasilamani

paginate:         5

markdown:         redcarpet
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:      pygments
safe:             false
lsi:              false

permalink:        /:title/
relative_permalinks: false

img-url:          http://localhost:4000/public/img
download-url:     http://localhost:4000/public/downloads

disqus:           false
analytics:        false